<?php
// Custom locations - auto-generated by Maps.php
return array (
  0 => 
  array (
    'name' => 'Rams Electronics',
    'lat' => 10.132741,
    'lng' => 124.83902,
    'category' => 'Electronic Shop',
    'type' => 'custom',
  ),
  1 => 
  array (
    'name' => 'Sebu cha',
    'lat' => 10.133026,
    'lng' => 124.836997,
    'category' => 'Restaurant',
    'type' => 'custom',
  ),
  2 => 
  array (
    'name' => 'Saint Joseph Jr. High School',
    'lat' => 10.133411,
    'lng' => 124.837657,
    'category' => 'School',
    'type' => 'custom',
  ),
  3 => 
  array (
    'name' => 'Abgao Basket Ball Gym',
    'lat' => 10.13316,
    'lng' => 124.842279,
    'category' => 'Sports',
    'type' => 'custom',
  ),
  4 => 
  array (
    'name' => 'Brodeth Marketing',
    'lat' => 10.13169,
    'lng' => 124.840046,
    'category' => 'Market',
    'type' => 'custom',
  ),
  5 => 
  array (
    'name' => 'Maasin Capitol',
    'lat' => 10.133947,
    'lng' => 124.859544,
    'category' => 'Government',
    'type' => 'custom',
  ),
  6 => 
  array (
    'name' => 'Mr.Work',
    'lat' => 10.132091,
    'lng' => 124.853823,
    'category' => 'Restaurant',
    'type' => 'custom',
  ),
);
?>