<?php
session_start();
include("db_connect.php");

// LOCATION DATABASE - Predefined Maasin Locations
$predefinedLocations = [
    [
        "id" => 1,
        "name" => "Maasin City Fire Station",
        "lat" => 10.132752,
        "lng" => 124.834795,
        "category" => "Fire Station",
        "type" => "predefined"
    ],
    [
        "id" => 2,
        "name" => "Maasin City Park",
        "lat" => 10.132377,
        "lng" => 124.838700,
        "category" => "Park",
        "type" => "predefined"
    ],
    [
        "id" => 3,
        "name" => "Maasin Cathedral",
        "lat" => 10.132666,
        "lng" => 124.837963,
        "category" => "Religious",
        "type" => "predefined"
    ],
    [
        "id" => 4,
        "name" => "Maasin Gaisano Grand Mall",
        "lat" => 10.133893,
        "lng" => 124.84156,
        "category" => "Shopping",
        "type" => "predefined"
    ],
    [
        "id" => 5,
        "name" => "Port of Maasin",
        "lat" => 10.131433,
        "lng" => 124.841333,
        "category" => "Port",
        "type" => "predefined"
    ],
    [
        "id" => 6,
        "name" => "Maasin City Terminal",
        "lat" => 10.131666,
        "lng" => 124.834722,
        "category" => "Terminal",
        "type" => "predefined"
    ],
    [
        "id" => 7,
        "name" => "Tagnipa Gym",
        "lat" => 10.132172,
        "lng" => 124.835468,
        "category" => "Sports",
        "type" => "predefined"
    ],
    [
        "id" => 8,
        "name" => "Saint Joseph College",
        "lat" => 10.132166,
        "lng" => 124.837463,
        "category" => "School",
        "type" => "predefined"
    ],
    [
        "id" => 9,
        "name" => "Maasin SSS (Social Security System)",
        "lat" => 10.133353,
        "lng" => 124.845656,
        "category" => "Government",
        "type" => "predefined"
    ]
];

// LOCATION DATABASE FUNCTIONS
// ===========================

/**
 * Get all locations (predefined + custom)
 * Returns array of location objects
 */
function getAllLocations() {
    global $predefinedLocations;
    $customLocations = getCustomLocations();
    return array_merge($predefinedLocations, $customLocations);
}

/**
 * Get custom saved locations from file
 */
function getCustomLocations() {
    $customLocationsFile = __DIR__ . '/custom_locations.php';
    
    if (file_exists($customLocationsFile)) {
        // Get the array from the custom locations file
        $customLocations = include($customLocationsFile);
        return is_array($customLocations) ? $customLocations : [];
    }
    
    return [];
}

/**
 * Save custom location to file
 */
function saveCustomLocation($name, $lat, $lng, $category = 'Other') {
    try {
        // Validate inputs
        if (empty($name) || !is_numeric($lat) || !is_numeric($lng)) {
            return false;
        }
        
        // Check if location already exists
        $existing = getCustomLocations();
        foreach ($existing as $loc) {
            if (strtolower($loc['name']) === strtolower($name) && $loc['category'] === $category) {
                return false; // Already exists
            }
        }
        
        // Create new location
        $newLocation = [
            "name" => $name,
            "lat" => floatval($lat),
            "lng" => floatval($lng),
            "category" => $category,
            "type" => "custom"
        ];
        
        // Add to existing locations
        $allCustom = $existing;
        $allCustom[] = $newLocation;
        
        // Write to custom_locations.php file
        $customLocationsFile = __DIR__ . '/custom_locations.php';
        $php_code = "<?php\n// Custom locations - auto-generated by Maps.php\nreturn " . var_export($allCustom, true) . ";\n?>";
        
        $result = file_put_contents($customLocationsFile, $php_code);
        return $result !== false;
    } catch (Exception $e) {
        error_log("Error saving location: " . $e->getMessage());
        return false;
    }
}

/**
 * Get location by name
 */
function getLocationByName($name) {
    $locations = getAllLocations();
    foreach ($locations as $loc) {
        if (strtolower($loc['name']) === strtolower($name)) {
            return $loc;
        }
    }
    return null;
}

/**
 * Get location by coordinates
 */
function getLocationByCoords($lat, $lng, $tolerance = 0.0001) {
    $locations = getAllLocations();
    foreach ($locations as $loc) {
        if (abs($loc['lat'] - $lat) < $tolerance && abs($loc['lng'] - $lng) < $tolerance) {
            return $loc;
        }
    }
    return null;
}

/**
 * Search locations by name (substring match)
 */
function searchLocations($query) {
    $locations = getAllLocations();
    $results = [];
    $query = strtolower($query);
    
    foreach ($locations as $loc) {
        if (strpos(strtolower($loc['name']), $query) !== false) {
            $results[] = $loc;
        }
    }
    
    return $results;
}

// API ENDPOINT - Handle JSON requests from other pages
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_GET['api'])) {
    header('Content-Type: application/json');
    
    $action = $_GET['api'];
    
    switch ($action) {
        case 'get_all':
            echo json_encode(['success' => true, 'locations' => getAllLocations()]);
            break;
            
        case 'get_predefined':
            global $predefinedLocations;
            echo json_encode(['success' => true, 'locations' => $predefinedLocations]);
            break;
            
        case 'search':
            $query = $_GET['q'] ?? '';
            $results = searchLocations($query);
            echo json_encode(['success' => true, 'locations' => $results]);
            break;
            
        case 'save_custom':
            $data = json_decode(file_get_contents('php://input'), true);
            
            // Validate required fields
            if (empty($data['name']) || empty($data['lat']) || empty($data['lng'])) {
                echo json_encode(['success' => false, 'error' => 'Missing required fields']);
                break;
            }
            
            // Server-side validation only, actual storage is client-side (localStorage)
            $result = saveCustomLocation($data['name'], floatval($data['lat']), floatval($data['lng']), $data['category'] ?? 'Other');
            echo json_encode(['success' => $result]);
            break;
            
        default:
            echo json_encode(['success' => false, 'error' => 'Unknown action']);
    }
    exit;
}

// If accessed directly (not as API), show location map interface
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Location Database Manager - BFP Fuel System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <style>
        :root { 
            --bfp-red: #B22222; 
            --primary-bg: #1e1e2d; 
            --secondary-bg: #2a2a3e;
            --accent-color: #5d5dff;
            --text-primary: white;
            --text-secondary: #a2a2c2;
            --border-color: rgba(255,255,255,0.05);
            --transition: 0.3s;
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body { 
            font-family: 'Segoe UI', Arial, sans-serif; 
            background: var(--primary-bg);
            height: 100vh;
            overflow: hidden;
            color: var(--text-primary);
        }

        .container {
            display: flex;
            height: 100vh;
            flex-direction: column;
        }

        .content {
            display: flex;
            flex: 1;
            gap: 20px;
            padding: 20px;
            min-height: 0;
        }

        .map-wrapper {
            flex: 1;
            background: var(--secondary-bg);
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.3);
            padding: 15px;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            border: 1px solid var(--border-color);
        }

        #map {
            flex: 1;
            border-radius: 8px;
            z-index: 1;
        }

        .sidebar {
            width: 320px;
            background: var(--secondary-bg);
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.3);
            padding: 20px;
            display: flex;
            flex-direction: column;
            gap: 15px;
            overflow: hidden;
            border: 1px solid var(--border-color);
        }

        .sidebar h3 {
            color: var(--accent-color);
            font-size: 1rem;
            margin-bottom: 10px;
            padding-bottom: 10px;
            border-bottom: 2px solid var(--accent-color);
            font-weight: 600;
        }

        .search-box {
            display: flex;
            gap: 8px;
        }

        .search-box input {
            flex: 1;
            padding: 10px 12px;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            font-size: 0.9rem;
            background: rgba(255,255,255,0.03);
            color: var(--text-primary);
            transition: all var(--transition);
        }

        .search-box input:focus {
            outline: none;
            border-color: var(--accent-color);
            background: rgba(93,93,255,0.08);
            box-shadow: 0 0 0 3px rgba(93,93,255,0.1);
        }

        .search-box button {
            padding: 10px 15px;
            background: var(--accent-color);
            color: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all var(--transition);
            font-weight: 600;
        }

        .search-box button:hover { 
            background: #4a4aff;
            transform: translateY(-1px);
            box-shadow: 0 4px 8px rgba(93,93,255,0.3);
        }

        .location-list {
            flex: 1;
            overflow-y: auto;
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .location-list::-webkit-scrollbar {
            width: 6px;
        }

        .location-list::-webkit-scrollbar-track {
            background: transparent;
        }

        .location-list::-webkit-scrollbar-thumb {
            background: rgba(93,93,255,0.3);
            border-radius: 3px;
        }

        .location-list::-webkit-scrollbar-thumb:hover {
            background: rgba(93,93,255,0.5);
        }

        .location-item {
            padding: 12px;
            background: rgba(93,93,255,0.08);
            border: 1px solid rgba(93,93,255,0.2);
            border-radius: 8px;
            cursor: pointer;
            transition: all var(--transition);
            font-size: 0.9rem;
        }

        .location-item:hover {
            background: rgba(93,93,255,0.15);
            border-color: var(--accent-color);
            transform: translateX(4px);
            box-shadow: 0 4px 8px rgba(93,93,255,0.2);
        }

        .location-name {
            font-weight: 600;
            color: var(--accent-color);
            margin-bottom: 4px;
        }

        .location-meta {
            font-size: 0.8rem;
            color: var(--text-secondary);
        }

        .category-badge {
            display: inline-block;
            background: rgba(93,93,255,0.2);
            color: var(--accent-color);
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 0.75rem;
            margin-top: 5px;
            border: 1px solid rgba(93,93,255,0.3);
            font-weight: 500;
        }

        .category-buttons {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
            margin-bottom: 15px;
        }

        .category-btn {
            padding: 8px 12px;
            background: rgba(255,255,255,0.05);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            cursor: pointer;
            font-size: 0.85rem;
            transition: all var(--transition);
            color: var(--text-secondary);
            font-weight: 500;
        }

        .category-btn:hover {
            background: rgba(93,93,255,0.1);
            border-color: var(--accent-color);
            color: var(--accent-color);
        }

        .category-btn.active {
            background: linear-gradient(90deg, rgba(93,93,255,0.2) 0%, rgba(93,93,255,0) 100%);
            color: white;
            border-color: var(--accent-color);
            border-left: 3px solid var(--accent-color);
            padding-left: 10px;
        }

        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0,0,0,0.7);
            z-index: 1000;
            align-items: center;
            justify-content: center;
            animation: fadeIn 0.3s ease;
        }

        .modal.active { display: flex; }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        @keyframes slideUp {
            from { transform: translateY(20px); opacity: 0; }
            to { transform: translateY(0); opacity: 1; }
        }

        .modal-content {
            background: var(--secondary-bg);
            padding: 30px;
            border-radius: 12px;
            max-width: 400px;
            width: 90%;
            box-shadow: 0 10px 40px rgba(0,0,0,0.4);
            border: 1px solid var(--border-color);
            animation: slideUp 0.3s ease;
        }

        .modal-content h2 {
            color: var(--accent-color);
            margin-bottom: 20px;
            font-size: 1.3rem;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: var(--text-primary);
            font-size: 0.9rem;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 12px;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            font-size: 0.9rem;
            background: rgba(255,255,255,0.03);
            color: var(--text-primary);
            transition: all var(--transition);
        }

        .form-group input::placeholder {
            color: rgba(162,162,194,0.6);
        }

        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: var(--accent-color);
            background: rgba(93,93,255,0.08);
            box-shadow: 0 0 0 3px rgba(93,93,255,0.1);
        }

        .modal-buttons {
            display: flex;
            gap: 10px;
            margin-top: 20px;
        }

        .modal-buttons button {
            flex: 1;
            padding: 12px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            transition: all var(--transition);
            font-size: 0.95rem;
        }

        .btn-save {
            background: linear-gradient(90deg, var(--accent-color) 0%, #7a7aff 100%);
            color: white;
            border: 1px solid var(--accent-color);
        }

        .btn-save:hover { 
            background: linear-gradient(90deg, #4a4aff 0%, #6a6aff 100%);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(93,93,255,0.3);
        }

        .btn-cancel {
            background: rgba(255,255,255,0.05);
            color: var(--text-secondary);
            border: 1px solid var(--border-color);
        }

        .btn-cancel:hover { 
            background: rgba(255,255,255,0.08);
            color: var(--text-primary);
            border-color: rgba(255,255,255,0.1);
        }

        .empty-state {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
            color: var(--text-secondary);
            font-size: 1rem;
            text-align: center;
        }

        .add-location-btn {
            width: 100%;
            padding: 12px;
            background: linear-gradient(90deg, var(--accent-color) 0%, #7a7aff 100%);
            color: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            margin-top: auto;
            transition: all var(--transition);
            font-size: 0.95rem;
            flex-shrink: 0;
        }

        .add-location-btn:hover {
            background: linear-gradient(90deg, #4a4aff 0%, #6a6aff 100%);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(93,93,255,0.3);
        }

        .header {
            background: linear-gradient(90deg, var(--bfp-red) 60%, #FF4500 100%);
            color: white;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: 0 2px 8px rgba(0,0,0,0.3);
        }

        .header h1 { 
            font-size: 1.8rem; 
            margin: 0; 
            flex: 1;
        }

        .return-btn {
            padding: 10px 20px;
            background: rgba(255,255,255,0.2);
            color: white;
            border: 1px solid rgba(255,255,255,0.3);
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            transition: all var(--transition);
            display: flex;
            align-items: center;
            gap: 8px;
            text-decoration: none;
        }

        .return-btn:hover {
            background: rgba(255,255,255,0.3);
            border-color: rgba(255,255,255,0.5);
            transform: translateX(-2px);
        }

        .map-hint {
            position: absolute;
            top: 20px;
            left: 50%;
            transform: translateX(-50%);
            background: rgba(93,93,255,0.2);
            border: 1px solid var(--accent-color);
            color: var(--accent-color);
            padding: 10px 15px;
            border-radius: 8px;
            font-size: 0.9rem;
            pointer-events: none;
            display: none;
            z-index: 100;
        }

        .map-hint.show {
            display: block;
        }
    </style>
</head>
<body>

<div class="header">
    <h1>📍 Location Database Manager</h1>
    <a href="CreateForm.php" class="return-btn"><i class="fas fa-arrow-left"></i> Return to Form</a>
</div>

<div class="container">
    <div class="content">
        <div class="map-wrapper">
            <div id="map"></div>
        </div>

        <div class="sidebar">
            <h3>🔍 Search Locations</h3>
            <div class="search-box">
                <input type="text" id="searchInput" placeholder="Search location...">
                <button onclick="searchLocations()"><i class="fas fa-search"></i></button>
            </div>

            <h3>🏷️ Filter by Category</h3>
            <div class="category-buttons">
                <button class="category-btn active" onclick="filterCategory('all')">All</button>
                <button class="category-btn" onclick="filterCategory('Fire Station')">Fire Station</button>
                <button class="category-btn" onclick="filterCategory('Park')">Park</button>
                <button class="category-btn" onclick="filterCategory('School')">School</button>
                <button class="category-btn" onclick="filterCategory('Shopping')">Shopping</button>
                <button class="category-btn" onclick="filterCategory('Hospital')">Hospital</button>
                <button class="category-btn" onclick="filterCategory('Terminal')">Terminal</button>
            </div>

            <h3>📌 Locations (<?php echo count(getAllLocations()); ?>)</h3>
            <div class="location-list" id="locationList">
                <div class="empty-state">Loading locations...</div>
            </div>

            <button onclick="openAddLocationModal()" class="add-location-btn">
                + Add New Location
            </button>
        </div>
    </div>
</div>

<!-- Add Location Modal -->
<div class="modal" id="addLocationModal">
    <div class="modal-content">
        <h2>Add New Location</h2>
        <form id="addLocationForm">
            <div class="form-group">
                <label>Location Name *</label>
                <input type="text" id="locationName" required>
            </div>
            <div class="form-group">
                <label>Category *</label>
                <select id="locationCategory" required>
                    <option value="">Select Category</option>
                    <option value="Fire Station">Fire Station</option>
                    <option value="Park">Park</option>
                    <option value="School">School</option>
                    <option value="Hospital">Hospital</option>
                    <option value="Shopping">Shopping</option>
                    <option value="Religious">Religious</option>
                    <option value="Sports">Sports</option>
                    <option value="Terminal">Terminal</option>
                    <option value="Government">Government</option>
                    <option value="Port">Port</option>
                    <option value="Other">Other</option>
                </select>
            </div>
            <div class="form-group" id="customCategoryGroup" style="display: none;">
                <label>Custom Category *</label>
                <input type="text" id="customCategory" placeholder="Enter custom category" maxlength="50">
            </div>
            <div class="form-group">
                <label>Latitude *</label>
                <input type="number" id="locationLat" step="0.000001" required>
            </div>
            <div class="form-group">
                <label>Longitude *</label>
                <input type="number" id="locationLng" step="0.000001" required>
            </div>
            <div class="modal-buttons">
                <button type="submit" class="btn-save">💾 Save Location</button>
                <button type="button" class="btn-cancel" onclick="closeAddLocationModal()">Cancel</button>
            </div>
        </form>
    </div>
</div>

<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script>
    // Initialize map
    const map = L.map('map').setView([10.132752, 124.834795], 14);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    const markers = new Map();
    let allLocations = [];
    let filteredCategory = 'all';

    /**
     * Load custom locations from server file
     */
    function getLocalStorageLocations() {
        // Locations now come from server-side custom_locations.php file
        // They're included in the main allLocations array, so this is not needed anymore
        return [];
    }

    /**
     * Load and display all locations from server
     */
    async function loadLocations() {
        try {
            const response = await fetch(window.location.href + '?api=get_all', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' }
            });
            const data = await response.json();
            
            if (data.success) {
                // All locations (predefined + custom from file) are in data.locations
                allLocations = data.locations;
                displayLocations(allLocations);
            }
        } catch (error) {
            console.error('Error loading locations:', error);
            document.getElementById('locationList').innerHTML = '<div class="empty-state">Error loading locations</div>';
        }
    }

    /**
     * Display locations in sidebar and on map
     */
    function displayLocations(locations) {
        const listContainer = document.getElementById('locationList');
        
        if (locations.length === 0) {
            listContainer.innerHTML = '<div class="empty-state">No locations found</div>';
            clearMapMarkers();
            return;
        }

        listContainer.innerHTML = '';
        clearMapMarkers();

        locations.forEach((loc, index) => {
            // Create sidebar item
            const item = document.createElement('div');
            item.className = 'location-item';
            item.innerHTML = `
                <div class="location-name">${loc.name}</div>
                <div class="location-meta">
                    📍 ${loc.lat.toFixed(6)}, ${loc.lng.toFixed(6)}
                </div>
                <span class="category-badge">${loc.category}</span>
            `;
            item.addEventListener('click', () => focusLocation(loc));
            listContainer.appendChild(item);

            // Add marker to map
            const markerColor = loc.type === 'custom' ? 'blue' : 'red';
            const marker = L.circleMarker([loc.lat, loc.lng], {
                radius: 8,
                fillColor: markerColor,
                color: '#fff',
                weight: 2,
                opacity: 1,
                fillOpacity: 0.8
            }).addTo(map)
            .bindPopup(`<strong>${loc.name}</strong><br>${loc.category}<br>Lat: ${loc.lat.toFixed(6)}<br>Lng: ${loc.lng.toFixed(6)}`);

            // Use index as unique marker ID since custom locations might not have IDs
            markers.set(index + '-' + loc.name, marker);
        });
    }

    /**
     * Focus on a location on the map
     */
    function focusLocation(location) {
        map.setView([location.lat, location.lng], 16);
        const markerKey = Array.from(markers.keys()).find(key => 
            markers.get(key)._popup._content.includes(location.name)
        );
        if (markerKey) {
            markers.get(markerKey).openPopup();
        }
    }

    /**
     * Clear all markers from map
     */
    function clearMapMarkers() {
        markers.forEach(marker => map.removeLayer(marker));
        markers.clear();
    }

    /**
     * Search locations by query
     */
    function searchLocations() {
        const query = document.getElementById('searchInput').value.trim();
        if (!query) {
            displayLocations(allLocations);
            return;
        }

        const results = allLocations.filter(loc => 
            loc.name.toLowerCase().includes(query.toLowerCase())
        );
        displayLocations(results);
    }

    /**
     * Filter locations by category
     */
    function filterCategory(category) {
        // Update active button
        document.querySelectorAll('.category-btn').forEach(btn => {
            btn.classList.remove('active');
        });
        event.target.classList.add('active');

        filteredCategory = category;
        const filtered = category === 'all' 
            ? allLocations 
            : allLocations.filter(loc => loc.category === category);
        
        displayLocations(filtered);
    }

    /**
     * Open add location modal
     */
    function openAddLocationModal() {
        // Get current map center as default coordinates
        const center = map.getCenter();
        document.getElementById('locationLat').value = center.lat.toFixed(6);
        document.getElementById('locationLng').value = center.lng.toFixed(6);
        document.getElementById('addLocationModal').classList.add('active');
    }

    /**
     * Close add location modal
     */
    function closeAddLocationModal() {
        document.getElementById('addLocationModal').classList.remove('active');
        document.getElementById('addLocationForm').reset();
    }

    /**
     * Save new location to file via API
     */
    document.getElementById('addLocationForm').addEventListener('submit', async (e) => {
        e.preventDefault();

        let category = document.getElementById('locationCategory').value;
        
        // Use custom category if "Other" is selected and custom category is provided
        if (category === 'Other' && document.getElementById('customCategory').value.trim()) {
            category = document.getElementById('customCategory').value.trim();
        }

        const locationData = {
            name: document.getElementById('locationName').value.trim(),
            lat: parseFloat(document.getElementById('locationLat').value),
            lng: parseFloat(document.getElementById('locationLng').value),
            category: category
        };

        // Validate data
        if (!locationData.name) {
            alert('❌ Please enter a location name');
            return;
        }
        if (!locationData.category) {
            alert('❌ Please select a category');
            return;
        }
        if (isNaN(locationData.lat) || isNaN(locationData.lng)) {
            alert('❌ Please enter valid coordinates');
            return;
        }

        try {
            // Send to server to save to custom_locations.php file
            const response = await fetch(window.location.href + '?api=save_custom', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(locationData)
            });
            
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            
            const data = await response.json();

            if (data.success) {
                alert('✅ Location saved successfully!');
                closeAddLocationModal();
                loadLocations(); // Reload to show new location
            } else {
                alert('❌ Error saving location: ' + (data.error || 'Unknown error'));
                console.error('Save error:', data);
            }
        } catch (error) {
            console.error('Error:', error);
            alert('❌ Error saving location: ' + error.message);
        }
    });

    // Toggle custom category input when "Other" is selected
    document.getElementById('locationCategory').addEventListener('change', (e) => {
        const customCategoryGroup = document.getElementById('customCategoryGroup');
        if (e.target.value === 'Other') {
            customCategoryGroup.style.display = 'block';
        } else {
            customCategoryGroup.style.display = 'none';
        }
    });

    // Close modal when clicking outside
    document.getElementById('addLocationModal').addEventListener('click', (e) => {
        if (e.target.id === 'addLocationModal') {
            closeAddLocationModal();
        }
    });

    // Allow Enter key in search
    document.getElementById('searchInput').addEventListener('keypress', (e) => {
        if (e.key === 'Enter') searchLocations();
    });

    /**
     * Add location by clicking on map
     */
    let mapClickMode = false;
    map.on('click', function(e) {
        if (mapClickMode) {
            // Get clicked coordinates
            const lat = e.latlng.lat;
            const lng = e.latlng.lng;
            
            // Fill modal with coordinates
            document.getElementById('locationLat').value = lat.toFixed(6);
            document.getElementById('locationLng').value = lng.toFixed(6);
            document.getElementById('locationName').focus();
            
            // Close map click mode
            mapClickMode = false;
            document.querySelector('.map-wrapper').classList.remove('in-click-mode');
            
            // Hide hint
            const hint = document.querySelector('.map-hint');
            if (hint) hint.classList.remove('show');
        }
    });

    /**
     * Activate map click mode to select location
     */
    function activateMapClickMode() {
        mapClickMode = true;
        document.querySelector('.map-wrapper').classList.add('in-click-mode');
        
        // Show hint
        const hint = document.querySelector('.map-hint');
        if (hint) hint.classList.add('show');
    }

    // Load locations on page load
    loadLocations();
</script>

</body>
</html>
